name: Deploy to EC2

on:
  push:
    branches: [ main ] 
    
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/speako

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image (no cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          no-cache: true

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ env.IMAGE_NAME }}:latest
            sudo docker stop speako || true && sudo docker rm speako || true
            sudo docker run -d --env-file /home/ubuntu/.env -v /home/ubuntu/.env:/code/.env -v /home/ubuntu/nlp_model:/code/nlp_model --name speako -p 8000:8000 ${{ env.IMAGE_NAME }}:latest
